export const subscriptions = [
  {
    id: '1',
    serviceName: 'Netflix',
    category: 'OTT',
    price: 649,
    billingType: 'Monthly',
    startDate: '2024-01-15',
    nextDueDate: '2026-04-27',
    remark: 'Premium Plan',
    reminderEnabled: true,
    reminderDays: 3,
    status: 'Active',
    endDate: 'Present',
  },
  {
    id: '2',
    serviceName: 'Airtel',
    category: 'Mobile',
    price: 399,
    billingType: 'Monthly',
    startDate: '2024-03-01',
    nextDueDate: '2026-05-01',
    remark: 'Unlimited 5G',
    reminderEnabled: true,
    reminderDays: 5,
    status: 'Active',
    endDate: 'Present',
  },
  {
    id: '3',
    serviceName: 'WiFi',
    category: 'Internet',
    price: 799,
    billingType: 'Monthly',
    startDate: '2024-02-10',
    nextDueDate: '2026-05-10',
    remark: 'Fiber 200 Mbps',
    reminderEnabled: true,
    reminderDays: 7,
    status: 'Active',
    endDate: 'Present',
  },
  {
    id: '4',
    serviceName: 'Spotify',
    category: 'OTT',
    price: 119,
    billingType: 'Monthly',
    startDate: '2024-01-01',
    nextDueDate: '2026-05-01',
    remark: 'Premium',
    reminderEnabled: false,
    reminderDays: 3,
    status: 'Paused',
    endDate: 'Present',
  },
  {
    id: '5',
    serviceName: 'Amazon Prime',
    category: 'OTT',
    price: 1499,
    billingType: 'Yearly',
    startDate: '2024-06-01',
    nextDueDate: '2026-06-01',
    remark: 'Shopping + Video',
    reminderEnabled: true,
    reminderDays: 7,
    status: 'Active',
    endDate: 'Present',
  },
  {
    id: '6',
    serviceName: 'Tata Play',
    category: 'DTH',
    price: 499,
    billingType: 'Monthly',
    startDate: '2024-04-01',
    nextDueDate: '2026-05-04',
    remark: 'Family pack',
    reminderEnabled: true,
    reminderDays: 4,
    status: 'Cancelled',
    endDate: '2026-08-01',
  },
];

export const payments = [
  { id: '1', serviceName: 'Netflix', amount: 649, date: '2026-04-20', category: 'OTT' },
  { id: '2', serviceName: 'Airtel', amount: 399, date: '2026-04-01', category: 'Mobile' },
  { id: '3', serviceName: 'WiFi', amount: 799, date: '2026-04-10', category: 'Internet' },
  { id: '4', serviceName: 'Spotify', amount: 119, date: '2026-04-01', category: 'OTT' },
  { id: '5', serviceName: 'Tata Play', amount: 499, date: '2026-04-04', category: 'DTH' },
  { id: '6', serviceName: 'Netflix', amount: 649, date: '2026-03-20', category: 'OTT' },
  { id: '7', serviceName: 'Airtel', amount: 399, date: '2026-03-01', category: 'Mobile' },
  { id: '8', serviceName: 'WiFi', amount: 799, date: '2026-03-10', category: 'Internet' },
  { id: '9', serviceName: 'Spotify', amount: 119, date: '2026-03-01', category: 'OTT' },
  { id: '10', serviceName: 'Netflix', amount: 649, date: '2026-02-20', category: 'OTT' },
  { id: '11', serviceName: 'Airtel', amount: 399, date: '2026-02-01', category: 'Mobile' },
  { id: '12', serviceName: 'WiFi', amount: 799, date: '2026-02-10', category: 'Internet' },
];

export const categories = ['OTT', 'Mobile', 'Internet', 'DTH', 'Software', 'Cloud Storage'];

export const yearlySpendingData = [
  { year: '2024', amount: 45000 },
  { year: '2025', amount: 52000 },
  { year: '2026', amount: 28000 },
];

export const priceHistory = {
  Netflix: [
    { month: 'Jan', price: 649 },
    { month: 'Feb', price: 649 },
    { month: 'Mar', price: 649 },
    { month: 'Apr', price: 649 },
    { month: 'May', price: 649 },
    { month: 'Jun', price: 649 },
  ],
  Airtel: [
    { month: 'Jan', price: 299 },
    { month: 'Feb', price: 299 },
    { month: 'Mar', price: 399 },
    { month: 'Apr', price: 399 },
    { month: 'May', price: 399 },
    { month: 'Jun', price: 399 },
  ],
  WiFi: [
    { month: 'Jan', price: 699 },
    { month: 'Feb', price: 699 },
    { month: 'Mar', price: 799 },
    { month: 'Apr', price: 799 },
    { month: 'May', price: 799 },
    { month: 'Jun', price: 799 },
  ],
  Spotify: [
    { month: 'Jan', price: 119 },
    { month: 'Feb', price: 119 },
    { month: 'Mar', price: 119 },
    { month: 'Apr', price: 119 },
    { month: 'May', price: 119 },
    { month: 'Jun', price: 119 },
  ],
  'Amazon Prime': [
    { month: 'Jan', price: 125 },
    { month: 'Feb', price: 125 },
    { month: 'Mar', price: 125 },
    { month: 'Apr', price: 125 },
    { month: 'May', price: 125 },
    { month: 'Jun', price: 125 },
  ],
};

export const ottSpendingData = [
  { month: 'Jan', amount: 768 },
  { month: 'Feb', amount: 768 },
  { month: 'Mar', amount: 768 },
  { month: 'Apr', amount: 768 },
  { month: 'May', amount: 2267 },
  { month: 'Jun', amount: 768 },
];
